BenchBnb/BenchBnb/Controllers/LogInController.cs
using BenchBnb.FormModels;
using BenchBnb.Models;
using BenchBnb.Models.Data;
using BenchBnb.Models.Repositories;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace BenchBnb.Controllers
{
    public class LogInController : Controller
    {
        private Context context;

        public LogInController()
        {
            context = new Context();
        }

        [AllowAnonymous]
        public ActionResult Login()
        {
            var viewModel = new LogInFormModel();
            return View(viewModel);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LogInFormModel formModel)
        {
            if (ModelState.IsValidField("Email") && ModelState.IsValidField("Password"))
            {
                // TODO Get the user record from the database by their email.
                var userRepo = new UserRepo(context);

                User user = userRepo.GetByEmail(formModel.Email);

                // If we didn't get a user back from the database
                // or if the provided password doesn't match the password stored in the database
                // then login failed.
                if (user == null || !BCrypt.Net.BCrypt.Verify(formModel.Password, user.HashedPassword))
                {
                    ModelState.AddModelError("", "Login failed.");
                }
            }

            if (ModelState.IsValid)
            {
                // Login the user.
                FormsAuthentication.SetAuthCookie(formModel.Email, false);

                // Send them to the home page.
                return RedirectToAction("Index", "Bench");
            }

            return View(formModel);
        }

        [HttpPost]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();

            return RedirectToAction("Login");
        }
    }
}

BenchBnb/BenchBnb/Controllers/RegisterController.cs
using BenchBnb.FormModels;
using BenchBnb.Models;
using BenchBnb.Models.Data;
using BenchBnb.Models.Repositories;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace BenchBnb.Controllers
{
    public class RegisterController : Controller
    {
        private Context context;

        public RegisterController()
        {
            context = new Context();
        }

        [AllowAnonymous]
        public ActionResult Register()
        {
            var viewModel = new RegisterFormModel();
            return View(viewModel);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegisterFormModel formModel)
        {
            if (ModelState.IsValid)
            {
                // Create an instance of the user database model.
                User user = new User()
                {
                    Email = formModel.Email,
                    HashedPassword = formModel.Password,
                    Name = formModel.Name
                };
                string hashedPassword = BCrypt.Net.BCrypt.HashPassword(formModel.Password, 12);
                user.HashedPassword = hashedPassword;
                // TODO Save the user to the database.
                var userRepo = new UserRepo(context);
                try
                {
                    userRepo.Insert(user);
                    FormsAuthentication.SetAuthCookie(formModel.Email, false);

                    // Redirect the user to the "Home" page.
                    return RedirectToAction("Index", "Bench");
                }
                catch(DbUpdateException db)
                {

                    ModelState.AddModelError("", "Email is already in use.");
                }
                
            }

            return View(formModel);
        }

    }
}

BenchBnb/BenchBnb/Views/Register/Register.cshtml
@model BenchBnb.FormModels.RegisterFormModel
@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>

@using (Html.BeginForm("Register", "Register", FormMethod.Post, new { id = "register-form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", id = "emailText" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { @class = "form-control", id = "passwordText" })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Register" class="btn btn-default" id="submitBtt" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Login","Login", "LogIn")
   
</div>
<script src="~/Scripts/register.js"></script>