BenchBnb/BenchBnb/Models/Bench.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BenchBnb.Models
{
    public class Bench
    {
        public int Id { get; set; }
        [Required]
        public string Description { get; set; }
        public int NumSeats { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }
        public int UserId { get; set; }
        public DateTime CreatedOn { get; set; }
        public User User { get; set; }
        public List<Review> Reviews { get; set; }
        
        public Bench()
        {
            Reviews = new List<Review>();

        }
        public Bench (string description, int numSeats, float latitude, float longitude, User user)
        {
            Description = description;
            NumSeats = numSeats;
            Latitude = latitude;
            Longitude = longitude;
            User = user;
        }

        public double? AverageRating
        {
            get
            {
                if (Reviews.Count > 0)
                {
                    return Math.Round(Reviews.Average(r => r.Rating), 1);
                }
                else
                {
                    return null;
                }
            }
        }

        public string ShortDescription
        {
            get
            {
                string description = Description;
                string shortDescription = string.Empty;

                // Make sure that we have a description...
                if (!string.IsNullOrWhiteSpace(description))
                {
                    // Get a collection of the words in the description.
                    var words = description
                        .Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);

                    // If we have more than 10 words
                    // then take the first 10 and add "..." to the end
                    // otherwise just use the description as is. 
                    if (words.Length > 10)
                    {
                        shortDescription = string.Join(" ", words.Take(10)) + "...";
                    }
                    else
                    {
                        shortDescription = description;
                    }
                }

                return shortDescription;
            }
        }

    }
}

BenchBnb/BenchBnb/Controllers/BenchController.cs
using BenchBnb.FormModels;
using BenchBnb.Models.Data;
using BenchBnb.Models;
using BenchBnb.Models.Repositories;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Infrastructure;
using System.Web.Script.Serialization;
using System.Text;
namespace BenchBnb.Controllers
{
    
    public class BenchController : Controller
    {
        // GET: Homepage
        private Context context; 

        public BenchController()
        {
            context = new Context();
        }

        [HttpGet]
        [Authorize]
        public ActionResult Create(float? lat, float? lon)
        {
            var formModel = new CreateBench();
            if(lat!=null)
            {
                formModel.Latitude = lat.Value;
                formModel.Longitude = lon.Value;
            }
            return View("Create", formModel);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateBench formModel)
        {
            var repo = new BenchRepo(context);
            var userRepo = new UserRepo(context);
            try
            {
                User user = userRepo.GetByEmail(User.Identity.Name);
                var bench = new Bench(formModel.Description, formModel.NumSeats, formModel.Latitude, formModel.Longitude, user);
                bench.CreatedOn = DateTime.UtcNow;
                repo.Insert(bench);
                return RedirectToAction("Index");
            }
            catch (DbUpdateException ex)
            {
                //HandleDbUpdateException(ex);
            }
            return View("Create", formModel);
        }

        [HttpGet]
        public ActionResult Index()
        {
            var repo = new BenchRepo(context);
            IList<Bench> benches = repo.GetAllBenches();
            var json = new JavaScriptSerializer().Serialize(benches);

            return View("Index", benches);
        }

        public ActionResult Details(int benchId)
        {
            var formModel = new CreateBench();
            var benchRepo = new BenchRepo(context);
            var reviewRepo = new ReviewsRepo(context);
            var userRepo = new UserRepo(context);

            Bench bench = benchRepo.GetById(benchId);
            User user = userRepo.GetById(bench.UserId);


            string phrase = user.Name;
            string[] names = phrase.Split(' ');
            string lastName = names[1];
            StringBuilder uTag = new StringBuilder(names[0]);
            uTag.Append(" " + lastName[0]);
            formModel.userTag = uTag.ToString();
           
            formModel.Description = bench.Description;
            formModel.NumSeats = bench.NumSeats;
            formModel.Latitude = bench.Latitude;
            formModel.Longitude = bench.Longitude;
            formModel.CreatedOn = bench.CreatedOn;
            IList<Review> allReviews = reviewRepo.GetAllReviewsById(benchId);

            if (allReviews.Count == 0)
            {
                formModel.AverageRating = null;
            }
            else
            {
                float sum = 0f;
                foreach (Review rev in allReviews)
                {
                    sum += rev.Rating;
                }
                sum /= allReviews.Count;
                formModel.AverageRating = sum;
            }
            //previous short description code
            //string desc = formModel.Description;
            //StringBuilder sb = new StringBuilder();
            
            //int wordCount = 0;
            //for(int i = 0; i<desc.Length; i++)
            //{
            //    sb.Append(desc[i]);
            //    if(desc[i]== ' ')
            //    {
            //        wordCount++;
            //    }
            //    if(wordCount==10)
            //    {
            //        sb.Append("...");
            //        break;
            //    }
            //}
            //formModel.Description = sb.ToString();
            
            return View(formModel);
        }

        [HttpPost]
        public ActionResult Details(CreateBench formModel)
        { 
            return View(formModel);
        }

    }
}

BenchBnb/BenchBnb/Views/Bench/Create.cshtml
@model BenchBnb.FormModels.CreateBench
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Bench", FormMethod.Post, new { @class = "pure-form pure-form-aligned" }))
{
    @Html.AntiForgeryToken()

    <fieldset>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="pure-control-group">
            @Html.LabelFor(model => model.NumSeats, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.NumSeats, new { @class = "form-control", id = "numSeatsText" })
            @Html.ValidationMessageFor(model => model.NumSeats, "", new { @class = "text-danger" })
        </div>

        <div class="pure-control-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Description, new { @class = "form-control", id = "descriptionText" } )
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>

        <div class="pure-control-group">
            @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Latitude, new { @class = "form-control", id = "latText" })
            @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
        </div>

        <div class="pure-control-group">
            @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Longitude, new { @class = "form-control", id = "longText" })
            @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-default">Submit</button>
            </div>
       </div>
    </fieldset>
}

BenchBnb/BenchBnb/Views/Bench/Details.cshtml
@model BenchBnb.FormModels.CreateBench
@{
    ViewBag.Title = "Detail";
}


<h2>Bench Details</h2>

<div>
    
    <p>Description: @Model.Description</p>
    <p>Number Of Seats: @Model.NumSeats</p>
    <p>Latitude: @Model.Latitude</p>
    <p>Longitude: @Model.Longitude</p>
    @if(Model.AverageRating==null)
    {
        <p>Rating: No Reviews</p>
    }
    else
    { <p>Rating: @Model.AverageRating</p> }
   <p>Written by: @Model.userTag</p>
    <p>Date: @Model.CreatedOn</p>
</div>

BenchBnb/BenchBnb/Views/Bench/Index.cshtml
@model List<BenchBnb.Models.Bench>
@{
    ViewBag.Title = "Index";
}
<h2>Index</h2>

<title>Working with Openlayers</title>
<link rel="stylesheet" href="https://openlayers.org/en/v4.6.5/css/ol.css" type="text/css">
<!-- Openlayers CSS file-->
<style type="text/css">
    #map {
            width: 100%;
            height: 600px;
        }
</style>
    <!--Basic styling for map div,
    if height is not defined the div will show up with 0 px height  -->
<div id="map">
 <!-- Your map will be shown inside this div-->
</div>
<p>
    @Html.ActionLink("Add A Bench", "Create", new { }, new { @class = "pure-button pure-button-primary" })
</p>
<form id="bench-filtering" class="form-inline">
    <div class="form-group">
        <label for="minNumberOfSeats">Min:</label>
        <input type="number" id="minNumberOfSeats" class="form-control" />
    </div>
    <div class="form-group">
        <label for="maxNumberOfSeats">Max:</label>
        <input type="number" id="maxNumberOfSeats" class="form-control" />
    </div>
</form>

<div id="benches"></div>

<script src="https://openlayers.org/en/v4.6.5/build/ol.js" type="text/javascript"></script>
<!-- Openlayesr JS fIle -->
<script type="text/javascript" src="~/Scripts/map.js" type="text/javascript"></script>
<!-- Our map file -->
<script type="text/javascript" src="~/Scripts/benches-html.js" type="text/javascript"></script>
<script type="text/javascript" src="~/Scripts/main.js" type="text/javascript"></script>